### ISSUE TITLE
[de.nttr.stream maintainer] I'm flattered but please go easy on my server

### ISSUE THREAD

**Issue by kzshantonu** [ConcealNetwork/conceal-app#6]
Hi, I see you're singularly using my nitter instance in your app. I have no issue with that but I get a LOT of traffic from your app. There are many public instances [here](https://farside.link). Please load balance among many of them and mine instead of singularly hitting my server. Thanks

**Comment by ThrownLemon** [comment]
Apologies, will switch over to a load balanced system in the next update (this weekend most likely). Thanks for providing the service.
